### ISSUE TITLE
Confusing error when a space is inserted between comment lines

### ISSUE THREAD

**Issue by jtratner** [fulcrumgenomics/pybedlite#1]
I'm not sure whether this is valid according to BED spec, but if you accidentally introduce a blank line between comments, pybedlite will refuse to parse it (I believe, but still need to check, that pybedtools _will_ accept it).

```
example_file = "# some line\n# another line\n#\t\t third line\n\n#\n# Another comment\n# CHROM START END NAME\n# chr5\t1\t500"
with open("example.bed", "w") as fp:
    fp.write(example_file)
list(pybedlite.BedSource("example.txt"))
```

Produces this traceback:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../site-packages/pybedlite/bed_source.py", line 128, in __iter__
    + f"fields. On line {i} in {self._path} had only {len(fields)} fields"
AssertionError: BED records must conform to specifications, which requires at least 3 input fields. On line 3 in example.txt had only 1 fields
```

I'm totally open to idea that this is expected behavior, but it's actually a little nuanced to figure out what's going on.

Also, it appears that pybedtools is printing the line off by 1? (since it's actually line 4 in the file that has 1 field, line 3 is the line BEFORE the space).

**Comment by nh13** [comment]
@jtratner my reading of the spec that blank and whitespace-only lines should be ignored: https://samtools.github.io/hts-specs/BEDv1.pdf.  Therefore, I think the above is a bug!
