### ISSUE TITLE
Add py.typed to overlap_detector

### ISSUE THREAD

**Issue by msto** [fulcrumgenomics/pybedlite#28]
```
error: Skipping analyzing "pybedlite.overlap_detector": module is installed, but missing library stubs or py.typed marker  [import-untyped]
```

**Comment by clintval** [comment]
Ha! I was just going to do this today since I noticed it was missing late on Friday. Thanks for raising the issue!

**Comment by clintval** [comment]
I see we added the py.typed file here:

https://github.com/fulcrumgenomics/pybedlite/commit/9bbabbecccfeacf53d55950089214645419bd5d6

But that is not included in a recent release and I also think the file needs to not be in the root of the repo but in the package directory.
